FORMAT: 1A
HOST: http://seye.apiblueprint.org/api/v1/

# Sirius Eye

Sirius Eye is a social networking platform with the goal of fostering peace through art.

# Group Users

## Connected Users [/users?online,page]

### List Logged In [GET]

Connected users

+ Parameters
    - online: true (required)

+ Response 200 (application/json)

    + Attributes (array)
        - (object)
            - id: l123i4hj234kjlh
            - username: bob
        - (object)
            - id: l1223kj4hnnjj1l
            - username: alice

## Users [/users?page ]

### List All [GET]

System users

+ Response 200 (application/json)
    + Attributes (array)
        - (object)
            - id: l123i4hj234kjlh
            - username: bob
        - (object)
            - id: l1223kj4hnnjj1l
            - username: alice

## Friends Collection [/friends/{id}?page]

### List All Friends [GET]

List existing friends.

+ Parameters
    + page: 1 (optional, number) - The page of friends to return

+ Response 200 (application/json)

    + Attributes (array)
        - (object)
            - id: skdjfh423
            - username: testuser
        - (object)
            - id: ksjdfh3455
            - username: testuser0
        - (object)
            - id: dlknfglw45s
            - username: testuser1

### Add A Friend [POST]

Add a user as a friend.

+ Request (application/json)

    + Attributes
        - email: test@example.com

+ Response 201 (application/json)

    + Headers

            Location: /friends/i2u3r8dh

    + Attributes
        - id: 23kjh234jkh5
        - username: testuser

### Remove A Friend [DELETE]

+ Parameters
    - id: sjkwehr4235kj23

+ Response 200
    + Attributes
        - id: sjkwehr4235kj23
        - username: testuser

# Group Authentication

## Login [/login]

### Authenticate [POST]

+ Request (application/json)

        - email
        - password

+ Response 201 (application/json)

        - token: lqk34jh2lk34hjjh45

## Params [/login/params]

+ Attributes
    - service: Google - Appropriately capitalized oauth endpoint
    - endpoint: https://accounts.google.com/o/oauth2/v2/auth - Auth endpoint within service
    - response_type: token- Type of authorization to grant
    - client_id: `googl-234kjh3krjh4234` - CVlient Id within authorizing service
    - redirect_uri: https://siriuseye.com/login/confirm?code=23oi4u2nj - URI within Sirius Eye to redirect to
    - scope: email - Scope of grant
    - url: https://accounts.google.com/o/oauth2/v2/auth?scope=email%20profile&state=%2Fprofile&redirect_uri=https%3A%2F%2Foauth2-login-demo.appspot.com%2Foauthcallback&response_type=token&client_id=812741506391.apps.googleusercontent.com&nonce=DgkRrHXmyu3KLd0KDdfq
            
### List [GET]

+ Response 200 (application/json)

    + Attributes (array)
        - (object)
            - service: google
            - response_type: token
            - client_id: googl-234kjh3krjh4234
            - redirect_uri: https://siriuseye.com/login/confirm?code=23oi4u2nj
            - scope: read
            - url
        - (object)
            - service: facebook
            - response_type: token
            - client_id: fb-234kjh3krjh4234
            - redirect_uri: https://siriuseye.com/login/confirm?code=2345i8dfj
            - scope: read

# Group Blogs

## Blogs [/blogs?tag]

Blog posts

### List Posts [GET]

+ Parameters
    - tag: lifestyle - Tag to filter on
    
+ Response 200 (application/json)

    + Attributes (array)
        - (object)
            - title: `Easy-E's Latest`
            - body: This is a blog post
            - published_at: `2014-02-01T014:28:56.321-10:00`
            - created_at: `2014-02-01T10:28:56.321-10:00`
            - last_edited_at: `2014-02-01T11:28:56.321-10:00`
        - (object)
            - title: `Hard-E's Latest`
            - body: This is a blog post
            - published_at: `2014-02-01T014:28:56.321-10:00`
            - created_at: `2014-02-01T10:28:56.321-10:00`
            - last_edited_at: `2014-02-01T11:28:56.321-10:00`

# Group Tags

## Manage Tags [/tags]

Categorizations

### List Tags [GET]

+ Response 200 (application/json)

    + Attributes (array)
        - (object)
            - name: Music
            - id: we3jklrh423
        - (object)
            - name: News
            - id: ioj31234klj

### Add Tag

+ Request

    + Attributes
      - name: New Tag
      - parent: kl3rhj234j - parent id

+ Response 200 (application/json)

    + Attributes (array)
        - (object)
            - name: Music
            - id: we3jklrh423
        - (object)
            - name: News
            - id: ioj31234klj


# Group Reactions

# Group Locations

## Manage Locations [/locations?lat,long]

Check-ins

### List Posts [GET]

+ Response 200 (application/json)

    + Attributes (array)
        - (object)
            - name: Local 16
            - description: Bar

# Group Events

## Manage Events [/events]

Planned events
