FORMAT: 1A
HOST: http://seye.apiblueprint.org/api/v1/

# Sirius Eye

Sirius Eye is a social networking platform with the goal of fostering peace through art.

# Group Users

## Friends Collection [/friends?page]

### List All Friends [GET]

List existing friends.

+ Parameters
    + page: 1 (optional, number) - The page of friends to return

+ Response 200 (application/json)

    + Attributes (array)
        - (object)
            - id: skdjfh423
            - username: testuser
        - (object)
            - id: ksjdfh3455
            - username: testuser0
        - (object)
            - id: dlknfglw45s
            - username: testuser1

### Add A Friend [POST]

Add a user as a friend.

+ Request (application/json)

    + Attributes
        - email: test@example.com

+ Response 201 (application/json)

    + Headers

            Location: /friends/i2u3r8dh

    + Attributes
        - id: 23kjh234jkh5
        - username: testuser

## Users [/users]

### List [GET]

+ Response 201 (application/json)

              - id: l123i4hj234kjlh
                username: bob
              - id: l1223kj4hnnjj1l
                username: alice


# Group Authentication

## Login [/login]

### Authenticate [POST]

+ Request (application/json)

        - email
        - password

+ Response 201 (application/json)

        - token: lqk34jh2lk34hjjh45


## Params [/login/params]
            
### List [GET]

+ Response 200 (application/json)

    + Attributes (array)
        - (object)
            - service: google
            - response_type: token
            - client_id: googl-234kjh3krjh4234
            - redirect_uri: https://siriuseye.com/login/confirm?code=23oi4u2nj
            - scope: read
        - (object)
            - service: facebook
            - response_type: token
            - client_id: fb-234kjh3krjh4234
            - redirect_uri: https://siriuseye.com/login/confirm?code=2345i8dfj
            - scope: read

# Group Blogs

## Manage Blogs [/blogs]

Blog posts

# Group Locations

## Manage Locations [/locations]

Check-ins

# Group Events

## Manage Events [/events]

Planned events

'