FORMAT: 1A
HOST: http://seye.apiblueprint.org/api/v1/

# Sirius Eye

Sirius Eye is a social networking platform with the goal of fostering peace through art.

## Friends Collection [/friends]

+ Attributes
    - id
    - username
    
+ Param

        - page

### List All Friends [GET]

+ Parameters
    + page: 1 (optional, number) - The page of questions to return

+ Response 200 (application/json)

### Create a New User [POST]

Add a user to the system.

+ Request (application/json)

        - email address

+ Response 201 (application/json)

    + Headers

            Location: /friends/i2u3r8dh

    + Body

            - id